eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.101.109:8761/eureka/

server:
  port: 8768
  
spring:
  application:
    name: eshop-one-service
    
feign: 
  hystrix:
    enabled: true